### ISSUE TITLE
There is an error in your example

### ISSUE THREAD

**Issue by baotiao** [RajivKurian/epoll-example#1]
when the read system call return error
            // EAGAIN or EWOULDBLOCK means we have no more data that can be read.
            // Everything else is a real error.
            if (!(errno == EAGAIN || errno == EWOULDBLOCK)) {
              perror("read");
              should_close = true;
            }
Here you should not close the fd, because EAGAIN mean that when a sock is noblocking, even the system notice the fd, but the fd don't have data. It is different for the peer close the fd.

**Comment by RajivKurian** [comment]
Hi Zongzhi. Thank you for raising the issue. Maybe I am misunderstanding but the `if` condition `DOES NOT` close the file when `errno == EAGAIN || errno == EWOULDBLOCK`.

``` cpp
    if (!(errno == EAGAIN || errno == EWOULDBLOCK)) {
        perror("read");
       should_close = true;
    }
```

Notice the `!`

**Comment by baotiao** [comment]
sorry. I miss the !...
